version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: events_manager
    networks:
      - freecodecamp
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass eChTelptB2spNWp92Pv_U2FJd8tT9jQg
    environment:
      - REDIS_REPLICATION_MODE=master


#  test-db:
#    image: postgres:13
#    ports:
#      - 5435:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123
#      POSTGRES_DB: nest
#    networks:
#      - freecodecamp
networks:
  freecodecamp: